version: 2
before:
  hooks:
    - go generate
    - go mod download

builds:
  - id: ytlive
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-X windsorf-youtube-live/internal/version.Version={{.Version}}"
      - "-X windsorf-youtube-live/internal/version.Commit={{.Commit}}"
      - "-X windsorf-youtube-live/internal/version.Date={{.Date}}"
    overrides:
      - goos: windows
        goarch: amd64
        flags: 
          - -trimpath
        env:
          - CC=zig cc -target x86_64-windows-gnu
          - CXX=zig c++ -target x86_64-windows-gnu
          - CGO_ENABLED=1
        ldflags:
          - -s -w -extldflags "-static"

      - goos: windows
        goarch: 'arm64'
        flags: 
          - -trimpath
        env:
          - CGO_ENABLED=1
          - CC=zig cc -target aarch64-windows-gnu
          - CXX=zig c++ -target aarch64-windows-gnu
        ldflags:
          - -s -w

      - goos: linux
        goarch: amd64
        flags: 
          - -trimpath
        env:
          - CC=zig cc -target x86_64-linux-musl
          - CXX=zig c++ -target x86_64-linux-musl
          - CGO_ENABLED=1
        ldflags:
          - -s -w
      
      - goos: linux
        goarch: arm64
        flags: 
          - -trimpath
        env:
          - CC=zig cc -target aarch64-linux-musl
          - CXX=zig c++ -target aarch64-linux-musl
          - CGO_ENABLED=1
        ldflags:
          - -s -w
      
      - goos: linux
        goarch: mips64
        flags: 
          - -trimpath
        env:
          - CC=zig cc -target mips64-linux-musl
          - CXX=zig c++ -target mips64-linux-musl
          - CGO_ENABLED=1
        ldflags:
          - -s -w

      
      - goos: darwin
        goarch: arm64
        flags: 
          - -trimpath
          - -buildmode=pie
        env:
          - CGO_ENABLED=1
          - CC=zig cc -target aarch64-macos-none -F{{ .Env.SDK_PATH }}/System/Library/Frameworks
          - CXX=zig c++ -target aarch64-macos-none -F{{ .Env.SDK_PATH }}/System/Library/Frameworks
        ldflags:
          - -s -w
      
      - goos: darwin
        goarch: amd64
        flags: 
          - -trimpath
          - -buildmode=pie
        env:
          - CGO_ENABLED=1
          - CC=zig cc -target x86_64-macos-none -F{{ .Env.SDK_PATH }}/System/Library/Frameworks
          - CXX=zig c++ -target x86_64-macos-none -F{{ .Env.SDK_PATH }}/System/Library/Frameworks
        ldflags:
          - -s -w 

changelog:
  sort: asc
  use: github
  format: "{{ .SHA }}: {{ .Message }} (@{{ . }}){{ end }}"
  filters:
    exclude:
      - "^test:"
      - "^test\\("
      - "^chore: update$"
      - "^chore: docs$"
      - "^docs: update$"
      - "^chore: schema$"
      - "^chore: typo$"
      - "^chore: auto-update generated files$"
      - "^chore: update schema$"
      - "^chore: schema update$"
      - "^chore\\(deps\\): "
      - "^(build|ci): "
      - "merge conflict"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\(.+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?(fix|refactor)(\(.+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: ^.*?docs?(\(.+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999

nfpms:
  - id: ytlive
    package_name: ytlive
    file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    vendor: YukLive
    homepage: https://yuklive.my.id
    maintainer: YukLive <yuklive@yuklive.my.id>
    description: YukLive is an utility to easier process TikTok and YouTube live streaming.
    license: MIT
    section: utils
    priority: extra
    ids:
      - ytlive

    formats:
      - deb
      - rpm